version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Alterado para mapear a porta 8081 do host para a porta 8081 do contêiner
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - minha_rede_comum
      - postgres
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=engsoft2
      - spring.rabbitmq.password=engsoft2
  rabbitmq:
    image: rabbitmq:management
    networks:
      - minha_rede_comum
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ms1        # Define o nome do banco de dados
      POSTGRES_USER: postgres   # Define o usuário
      POSTGRES_PASSWORD: 123456    # Define a senha
    networks:
      - postgres

networks:
  minha_rede_comum:
    external: true
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: