spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://postgres:5432/ms1
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081