spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/projarc-2
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081