spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://postgres:5432/ms2
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081